// @generated by protoc-gen-es v2.15.0 with parameter "target=ts,import_extension=ts"
// @generated from file gate/v1/gate.proto (package gate.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gate/v1/gate.proto.
 */
export const file_gate_v1_gate: GenFile = /*@__PURE__*/
  fileDesc("ChJnYXRlL3YxL2dhdGUucHJvdG8SB2dhdGUudjEigQEKEUF0dGFjaG1lbnRSZXF1ZXN0Eh0KBG9wZW4YASABKAsyDS5nYXRlLnYxLk9wZW5IABIfCgVpbnB1dBgCIAEoCzIOLmdhdGUudjEuSW5wdXRIABIhCgZyZXNpemUYAyABKAsyDy5nYXRlLnYxLlJlc2l6ZUgAQgkKB2NvbW1hbmQiSQoET3BlbhISCgpzZXNzaW9uX2lkGAEgASgJEhUKDXJlc3VtZV9vZmZzZXQYAiABKAQSFgoOc25hcHNob3RfYnl0ZXMYAyABKA0iJwoFSW5wdXQSEAoIc2VxdWVuY2UYASABKAQSDAoEZGF0YRgCIAEoDCI5CgZSZXNpemUSEAoIc2VxdWVuY2UYASABKAQSDwoHY29sdW1ucxgCIAEoDRIMCgRyb3dzGAMgASgNItQBCg9BdHRhY2htZW50RXZlbnQSIQoGb3BlbmVkGAEgASgLMg8uZ2F0ZS52MS5PcGVuZWRIABIwCg5zbmFwc2hvdF9jaHVuaxgCIAEoCzIWLmdhdGUudjEuU25hcHNob3RDaHVua0gAEhsKA2FjaxgDIAEoCzIMLmdhdGUudjEuQWNrSAASIQoGb3V0cHV0GAQgASgLMg8uZ2F0ZS52MS5PdXRwdXRIABIjCgdyZXNpemVkGAUgASgLMhAuZ2F0ZS52MS5SZXNpemVkSABCBwoFZXZlbnQiQQoGT3BlbmVkEhIKCnNlc3Npb25faWQYASABKAkSCwoDY3V0GAIgASgEEhYKDnNuYXBzaG90X2J5dGVzGAMgASgNIj4KDVNuYXBzaG90Q2h1bmsSEAoIcG9zaXRpb24YASABKA0SDAoEZGF0YRgCIAEoDBINCgVmaW5hbBgDIAEoCCIpCgNBY2sSEAoIc2VxdWVuY2UYASABKAQSEAoIYWNjZXB0ZWQYAiABKAgiKwoGT3V0cHV0EhMKC25leHRfb2Zmc2V0GAEgASgEEgwKBGRhdGEYAiABKAwiOAoHUmVzaXplZBIOCgZvZmZzZXQYASABKAQSDwoHY29sdW1ucxgCIAEoDRIMCgRyb3dzGAMgASgNIhEKD0dldFN0YXRzUmVxdWVzdCKMAQoQR2V0U3RhdHNSZXNwb25zZRIOCgZhY3RpdmUYASABKAMSEQoJY2FuY2VsbGVkGAIgASgEEhQKDHNsb3dfcmVhZGVycxgDIAEoBBIWCg5xdWV1ZV9jYXBhY2l0eRgEIAEoDRITCgtjaHVua19ieXRlcxgFIAEoDRISCgptYXhfcXVldWVkGAYgASgNMpQBCg1UZXJtaW5hbFByb2JlEkIKBkF0dGFjaBIaLmdhdGUudjEuQXR0YWNobWVudFJlcXVlc3QaGC5nYXRlLnYxLkF0dGFjaG1lbnRFdmVudCgBMAESPwoIR2V0U3RhdHMSGC5nYXRlLnYxLkdldFN0YXRzUmVxdWVzdBoZLmdhdGUudjEuR2V0U3RhdHNSZXNwb25zZUI1WjNjbGFua2VyYm94L3NwaWtlcy9yZWFsLWxvY2FsLXJwYy9nZW4vZ2F0ZS92MTtnYXRldjFiBnByb3RvMw");

/**
 * @generated from message gate.v1.AttachmentRequest
 */
export type AttachmentRequest = Message<"gate.v1.AttachmentRequest"> & {
  /**
   * @generated from oneof gate.v1.AttachmentRequest.command
   */
  command: {
    /**
     * @generated from field: gate.v1.Open open = 1;
     */
    value: Open;
    case: "open";
  } | {
    /**
     * @generated from field: gate.v1.Input input = 2;
     */
    value: Input;
    case: "input";
  } | {
    /**
     * @generated from field: gate.v1.Resize resize = 3;
     */
    value: Resize;
    case: "resize";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message gate.v1.AttachmentRequest.
 * Use `create(AttachmentRequestSchema)` to create a new message.
 */
export const AttachmentRequestSchema: GenMessage<AttachmentRequest> = /*@__PURE__*/
  messageDesc(file_gate_v1_gate, 0);

/**
 * @generated from message gate.v1.Open
 */
export type Open = Message<"gate.v1.Open"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: uint64 resume_offset = 2;
   */
  resumeOffset: bigint;

  /**
   * @generated from field: uint32 snapshot_bytes = 3;
   */
  snapshotBytes: number;
};

/**
 * Describes the message gate.v1.Open.
 * Use `create(OpenSchema)` to create a new message.
 */
export const OpenSchema: GenMessage<Open> = /*@__PURE__*/
  messageDesc(file_gate_v1_gate, 1);

/**
 * @generated from message gate.v1.Input
 */
export type Input = Message<"gate.v1.Input"> & {
  /**
   * @generated from field: uint64 sequence = 1;
   */
  sequence: bigint;

  /**
   * @generated from field: bytes data = 2;
   */
  data: Uint8Array;
};

/**
 * Describes the message gate.v1.Input.
 * Use `create(InputSchema)` to create a new message.
 */
export const InputSchema: GenMessage<Input> = /*@__PURE__*/
  messageDesc(file_gate_v1_gate, 2);

/**
 * @generated from message gate.v1.Resize
 */
export type Resize = Message<"gate.v1.Resize"> & {
  /**
   * @generated from field: uint64 sequence = 1;
   */
  sequence: bigint;

  /**
   * @generated from field: uint32 columns = 2;
   */
  columns: number;

  /**
   * @generated from field: uint32 rows = 3;
   */
  rows: number;
};

/**
 * Describes the message gate.v1.Resize.
 * Use `create(ResizeSchema)` to create a new message.
 */
export const ResizeSchema: GenMessage<Resize> = /*@__PURE__*/
  messageDesc(file_gate_v1_gate, 3);

/**
 * @generated from message gate.v1.AttachmentEvent
 */
export type AttachmentEvent = Message<"gate.v1.AttachmentEvent"> & {
  /**
   * @generated from oneof gate.v1.AttachmentEvent.event
   */
  event: {
    /**
     * @generated from field: gate.v1.Opened opened = 1;
     */
    value: Opened;
    case: "opened";
  } | {
    /**
     * @generated from field: gate.v1.SnapshotChunk snapshot_chunk = 2;
     */
    value: SnapshotChunk;
    case: "snapshotChunk";
  } | {
    /**
     * @generated from field: gate.v1.Ack ack = 3;
     */
    value: Ack;
    case: "ack";
  } | {
    /**
     * @generated from field: gate.v1.Output output = 4;
     */
    value: Output;
    case: "output";
  } | {
    /**
     * @generated from field: gate.v1.Resized resized = 5;
     */
    value: Resized;
    case: "resized";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message gate.v1.AttachmentEvent.
 * Use `create(AttachmentEventSchema)` to create a new message.
 */
export const AttachmentEventSchema: GenMessage<AttachmentEvent> = /*@__PURE__*/
  messageDesc(file_gate_v1_gate, 4);

/**
 * @generated from message gate.v1.Opened
 */
export type Opened = Message<"gate.v1.Opened"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: uint64 cut = 2;
   */
  cut: bigint;

  /**
   * @generated from field: uint32 snapshot_bytes = 3;
   */
  snapshotBytes: number;
};

/**
 * Describes the message gate.v1.Opened.
 * Use `create(OpenedSchema)` to create a new message.
 */
export const OpenedSchema: GenMessage<Opened> = /*@__PURE__*/
  messageDesc(file_gate_v1_gate, 5);

/**
 * @generated from message gate.v1.SnapshotChunk
 */
export type SnapshotChunk = Message<"gate.v1.SnapshotChunk"> & {
  /**
   * @generated from field: uint32 position = 1;
   */
  position: number;

  /**
   * @generated from field: bytes data = 2;
   */
  data: Uint8Array;

  /**
   * @generated from field: bool final = 3;
   */
  final: boolean;
};

/**
 * Describes the message gate.v1.SnapshotChunk.
 * Use `create(SnapshotChunkSchema)` to create a new message.
 */
export const SnapshotChunkSchema: GenMessage<SnapshotChunk> = /*@__PURE__*/
  messageDesc(file_gate_v1_gate, 6);

/**
 * @generated from message gate.v1.Ack
 */
export type Ack = Message<"gate.v1.Ack"> & {
  /**
   * @generated from field: uint64 sequence = 1;
   */
  sequence: bigint;

  /**
   * @generated from field: bool accepted = 2;
   */
  accepted: boolean;
};

/**
 * Describes the message gate.v1.Ack.
 * Use `create(AckSchema)` to create a new message.
 */
export const AckSchema: GenMessage<Ack> = /*@__PURE__*/
  messageDesc(file_gate_v1_gate, 7);

/**
 * @generated from message gate.v1.Output
 */
export type Output = Message<"gate.v1.Output"> & {
  /**
   * @generated from field: uint64 next_offset = 1;
   */
  nextOffset: bigint;

  /**
   * @generated from field: bytes data = 2;
   */
  data: Uint8Array;
};

/**
 * Describes the message gate.v1.Output.
 * Use `create(OutputSchema)` to create a new message.
 */
export const OutputSchema: GenMessage<Output> = /*@__PURE__*/
  messageDesc(file_gate_v1_gate, 8);

/**
 * @generated from message gate.v1.Resized
 */
export type Resized = Message<"gate.v1.Resized"> & {
  /**
   * @generated from field: uint64 offset = 1;
   */
  offset: bigint;

  /**
   * @generated from field: uint32 columns = 2;
   */
  columns: number;

  /**
   * @generated from field: uint32 rows = 3;
   */
  rows: number;
};

/**
 * Describes the message gate.v1.Resized.
 * Use `create(ResizedSchema)` to create a new message.
 */
export const ResizedSchema: GenMessage<Resized> = /*@__PURE__*/
  messageDesc(file_gate_v1_gate, 9);

/**
 * @generated from message gate.v1.GetStatsRequest
 */
export type GetStatsRequest = Message<"gate.v1.GetStatsRequest"> & {
};

/**
 * Describes the message gate.v1.GetStatsRequest.
 * Use `create(GetStatsRequestSchema)` to create a new message.
 */
export const GetStatsRequestSchema: GenMessage<GetStatsRequest> = /*@__PURE__*/
  messageDesc(file_gate_v1_gate, 10);

/**
 * @generated from message gate.v1.GetStatsResponse
 */
export type GetStatsResponse = Message<"gate.v1.GetStatsResponse"> & {
  /**
   * @generated from field: int64 active = 1;
   */
  active: bigint;

  /**
   * @generated from field: uint64 cancelled = 2;
   */
  cancelled: bigint;

  /**
   * @generated from field: uint64 slow_readers = 3;
   */
  slowReaders: bigint;

  /**
   * @generated from field: uint32 queue_capacity = 4;
   */
  queueCapacity: number;

  /**
   * @generated from field: uint32 chunk_bytes = 5;
   */
  chunkBytes: number;

  /**
   * @generated from field: uint32 max_queued = 6;
   */
  maxQueued: number;
};

/**
 * Describes the message gate.v1.GetStatsResponse.
 * Use `create(GetStatsResponseSchema)` to create a new message.
 */
export const GetStatsResponseSchema: GenMessage<GetStatsResponse> = /*@__PURE__*/
  messageDesc(file_gate_v1_gate, 11);

/**
 * A gate fixture, not a proposed complete product API.
 *
 * @generated from service gate.v1.TerminalProbe
 */
export const TerminalProbe: GenService<{
  /**
   * @generated from rpc gate.v1.TerminalProbe.Attach
   */
  attach: {
    methodKind: "bidi_streaming";
    input: typeof AttachmentRequestSchema;
    output: typeof AttachmentEventSchema;
  },
  /**
   * @generated from rpc gate.v1.TerminalProbe.GetStats
   */
  getStats: {
    methodKind: "unary";
    input: typeof GetStatsRequestSchema;
    output: typeof GetStatsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_gate_v1_gate, 0);

